### ISSUE TITLE
Obtain information on start and end position of a locus

### ISSUE THREAD

**Issue by ElicSY** [lcpilling/lcpilling.github.io#1]
Hi Luke, 
Can we get position information on the strat and end of a locus using get_loci? 
Many thanks and the best, 
Shuai Yuan

**Comment by lcpilling** [comment]
Hi Shuai Yuan,

Thanks for the contact. There are probably multiple ways to define a locus, but a quick/easy way would be to:

```r
# identify the loci using default parameters
#   500kb distance from lead SNP, etc.
gwas_loci = get_loci(gwas_example)

head(gwas_loci[ gwas_loci$lead==TRUE , ])
#>                SNP CHR        BP A1 A2     MAF        BETA         SE         P locus lead
#> 58431  rs111232683   1 107566149  G  C 0.34300  0.01352040 0.00161401  5.43e-17     1 TRUE
#> 75873  rs114254196   1 108635400  C  T 0.00848 -0.04481140 0.00818473  4.38e-08     2 TRUE
#> 83709  rs115292790   1 109310728  G  A 0.01360 -0.05639270 0.00608890  2.01e-20     3 TRUE
#> 91666   rs12740374   1 109817590  G  T 0.21900 -0.14822800 0.00166391 4.73e-305     4 TRUE
#> 98740  rs140266316   1 110326545  G  A 0.01630 -0.05770880 0.00597770  4.73e-22     5 TRUE
#> 120461    rs657801   1 111736389  T  C 0.31500  0.00905412 0.00150713  1.88e-09     6 TRUE

# for the "lead" SNPs get the base pair position +/-500kb
gwas_loci_dist = gwas_loci |> 
  dplyr::filter(lead==TRUE) |> 
  dplyr::mutate(
    BP_min = BP - 500000,
    BP_max = BP - 500000
  ) 

head(gwas_loci_dist)
#>           SNP CHR        BP A1 A2     MAF        BETA         SE         P locus lead    BP_min    BP_max
#> 1 rs111232683   1 107566149  G  C 0.34300  0.01352040 0.00161401  5.43e-17     1 TRUE 107066149 107066149
#> 2 rs114254196   1 108635400  C  T 0.00848 -0.04481140 0.00818473  4.38e-08     2 TRUE 108135400 108135400
#> 3 rs115292790   1 109310728  G  A 0.01360 -0.05639270 0.00608890  2.01e-20     3 TRUE 108810728 108810728
#> 4  rs12740374   1 109817590  G  T 0.21900 -0.14822800 0.00166391 4.73e-305     4 TRUE 109317590 109317590
#> 5 rs140266316   1 110326545  G  A 0.01630 -0.05770880 0.00597770  4.73e-22     5 TRUE 109826545 109826545
#> 6    rs657801   1 111736389  T  C 0.31500  0.00905412 0.00150713  1.88e-09     6 TRUE 111236389 111236389
```

If instead you want to know the distance between the furthest statistically significant SNPs within a locus you could do:

```r
# group by locus and identify min/max BP
gwas_loci_grouped = gwas_loci |>
  dplyr::group_by(locus) |>
  dplyr::summarize(
    BP_min = min(BP),
    BP_max = max(BP)
  ) 

head(gwas_loci_grouped)
#>   locus    BP_min    BP_max
#> 1     1 107536799 107648920
#> 2     2 108635400 108635400
#> 3     3 109020060 109317157
#> 4     4 109322296 110313595
#> 5     5 110318010 110458525
#> 6     6 111676597 111737183
```

In future please post any issues or questions on the package GitHub (here you have posted it to my website repository :)

All the best,
Luke

**Comment by ElicSY** [comment]
Dear Luke,

Thank you so much for the email and multiple ways to get the information on start and end of the locus.

Much appreciated! Also sorry for posting this in a wrong place!

Best regards,
Shuai

Shuai Yuan (he/him/his) | PhD, Researcher
Perelman School of Medicine | University of Pennsylvania
Institute of Environmental Medicine | Karolinska Institutet
Perelman Center for Advanced Medicine
3400 Civic Center Boulevard
Philadelphia, PA 19104
+1 445-260-8688
***@***.******@***.***> | ***@***.******@***.***>

From: Luke C. Pilling ***@***.***>
Date: Saturday, August 10, 2024 at 7:07 AM
To: lcpilling/lcpilling.github.io ***@***.***>
Cc: Shuai Yuan ***@***.***>, Author ***@***.***>
Subject: Re: [lcpilling/lcpilling.github.io] Obtain information on start and end position of a locus (Issue #1)

Hi Shuai Yuan,

Thanks for the contact. There are probably multiple ways to define a locus, but a quick/easy way would be to:

# identify the loci using default parameters

#   500kb distance from lead SNP, etc.

gwas_loci = get_loci(gwas_example)



head(gwas_loci[ gwas_loci$lead==TRUE , ])

#>                SNP CHR        BP A1 A2     MAF        BETA         SE         P locus lead

#> 58431  rs111232683   1 107566149  G  C 0.34300  0.01352040 0.00161401  5.43e-17     1 TRUE

#> 75873  rs114254196   1 108635400  C  T 0.00848 -0.04481140 0.00818473  4.38e-08     2 TRUE

#> 83709  rs115292790   1 109310728  G  A 0.01360 -0.05639270 0.00608890  2.01e-20     3 TRUE

#> 91666   rs12740374   1 109817590  G  T 0.21900 -0.14822800 0.00166391 4.73e-305     4 TRUE

#> 98740  rs140266316   1 110326545  G  A 0.01630 -0.05770880 0.00597770  4.73e-22     5 TRUE

#> 120461    rs657801   1 111736389  T  C 0.31500  0.00905412 0.00150713  1.88e-09     6 TRUE



# for the "lead" SNPs get the base pair position +/-500kb

gwas_loci_dist = gwas_loci |>

  dplyr::filter(lead==TRUE) |>

  dplyr::mutate(

    BP_min = BP - 500000,

    BP_max = BP - 500000

  )



head(gwas_loci_dist)

#>           SNP CHR        BP A1 A2     MAF        BETA         SE         P locus lead    BP_min    BP_max

#> 1 rs111232683   1 107566149  G  C 0.34300  0.01352040 0.00161401  5.43e-17     1 TRUE 107066149 107066149

#> 2 rs114254196   1 108635400  C  T 0.00848 -0.04481140 0.00818473  4.38e-08     2 TRUE 108135400 108135400

#> 3 rs115292790   1 109310728  G  A 0.01360 -0.05639270 0.00608890  2.01e-20     3 TRUE 108810728 108810728

#> 4  rs12740374   1 109817590  G  T 0.21900 -0.14822800 0.00166391 4.73e-305     4 TRUE 109317590 109317590

#> 5 rs140266316   1 110326545  G  A 0.01630 -0.05770880 0.00597770  4.73e-22     5 TRUE 109826545 109826545

#> 6    rs657801   1 111736389  T  C 0.31500  0.00905412 0.00150713  1.88e-09     6 TRUE 111236389 111236389

If instead you want to know the distance between the furthest statistically significant SNPs within a locus you could do:

# group by locus and identify min/max BP

gwas_loci_grouped = gwas_loci |>

  dplyr::group_by(locus) |>

  dplyr::summarize(

    BP_min = min(BP),

    BP_max = max(BP)

  )



head(gwas_loci_grouped)

#>   locus    BP_min    BP_max

#> 1     1 107536799 107648920

#> 2     2 108635400 108635400

#> 3     3 109020060 109317157

#> 4     4 109322296 110313595

#> 5     5 110318010 110458525

#> 6     6 111676597 111737183

In future please post any issues or questions on the package GitHub (here you have posted it to my website repository :)

All the best,
Luke
